name: Auto Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BLOG_SEC }}

      - name: Use latest Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          cache: npm

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: Asia/Taipei

      - name: Install dependencies
        run: npm install

      - name: Deploy using hexo-deployer-git
        env:
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
        run: |
          npm exec --package hexo -- hexo clean
          npm exec --package hexo -- hexo generate
          npm exec --package hexo -- hexo deploy
